import type { Metadata } from "next";
import { Inter ,Lato } from "next/font/google";
import "./globals.css";
import { Titulo } from "./components/ui/titulo/Titulo";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ weight:['100','300'], subsets:['latin']})


export const metadata: Metadata = {
  title: "Js Tareas",
  description: "Generated by next",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={lato.className}>
        <Titulo />
        {children}

      </body>
    </html>
  );
}
